### ISSUE TITLE
Make a TO-DO list

### ISSUE THREAD

**Issue by Naguumo** [Krish54491/Krish54491.github.io#6]
I can't remember all this stuff, make me a list so I can write this down.

- [x] Displays all current checklist items
  - Each item has a unchecked checkbox next to it
  - Clicking the checkbox moves it to the completed list
- [x] Displays a separate section of items marked as completed
  - These items should have a strikethrough on the text to indicate they are done
  - Also has a checkbox, but this one is already checked
- [x] Can add a new item to the checklist by entering it in a textbox and clicking a submit button
- [x] Styled using tailwind css
- [x] [EXTRA] Items stay the same even if I refresh the page
  - Store them in [localstorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)
- [ ] [EXTRA] Add a way to search items when there are too many
  - Can enter a filter string in a`input` textbox
  - Items that do not match the search string are faded/hard to see
